align with install_anaconda3, including converted to bash

diff --git a/install_miniconda3 b/install_miniconda3
--- a/install_miniconda3
+++ b/install_miniconda3
@@ -1,85 +1,95 @@
-#! /bin/csh -f
+#! /usr/bin/env bash
 #
-#  Install a miniconda3 python for astroquery.alma, and optionally casa6beta
-#  (with casa6=0 takes about 3 mins with a good internet connection)
+#  Install a miniconda3 python 
 #
 
-set sys = `uname -s`
+# some examples    @todo  fix this like done in install_anaconda3
+url=https://repo.anaconda.com/miniconda/Miniconda3-py39_24.5.0-0-Linux-x86_64.sh
+url=https://repo.anaconda.com/miniconda/Miniconda3-py39_24.7.1-0-MacOSX-arm64.sh
+url=https://repo.anaconda.com/miniconda/Miniconda3-py39_24.7.1-0-MacOSX-x86_64.sh
+url=https://repo.anaconda.com/miniconda/Miniconda3-py39_24.7.1-0-Linux-x86_64.sh
+url=https://repo.anaconda.com/miniconda/Miniconda3-py311_24.7.1-0-Linux-x86_64.sh
+url=https://repo.anaconda.com/miniconda/Miniconda3-py312_24.5.0-0-Linux-x86_64.sh
+url=https://repo.anaconda.com/miniconda/Miniconda3-py312_24.7.1-0-Linux-x86_64.sh
 
-#           68MB
-if ($sys == Linux) then
-  set mc3 = https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
-else if ($sys == Darwin) then
-  set mc3 = https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
-else
-  echo Bad sys=$sys
-  exit 1
-endif  
-set msh   = $mc3:t
-set dir   = `pwd`/miniconda3
-set casa6 = 0
-set conda = 1
-set pip   = 1
 
-# you better know what you are doing here
-foreach arg ($*)
-  set $arg
-end
+  dir=$(pwd)/miniconda3      # where miniconda will be located
+ wget=wget                   # use wgetc is you have my cashing version (wget=curl is also allowed)
+   os=$(uname -s)            # Handles Linux or Darwin, sorry no Windows
+  cpu=$(uname -m)            # Handles Linux or Darwin, sorry no Windows
+  dry=0                      # dry run?
+  
+#--HELP
 
-if (! -e $msh) then
-  wget $mc3
-  if ($status) then
-    curl $mc3 -o $msh
-    if ($status) exit 1
-  endif
-else
-  echo Found $msh
-endif
+# some help?    
+ if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
+    set +x
+    awk 'BEGIN{s=0} {if ($1=="#--HELP") s=1-s;  else if(s) print $0; }' $0
+    exit 0
+fi
+    
+# override parameters
+for arg in "$@"; do
+  export "$arg"
+done
+
+if [ "$os" = "Darwin" ]; then
+    os=MacOSX
+fi
+
+#mc3=$(printf $url $version $os $cpu)      # @todo to be implemented
+mc3=$url
+msh=$(basename $mc3)
+
+if [ $dry = 1 ]; then
+    echo $mc3
+    exit 0
+fi
+
+if [ -d $dir ]; then
+    echo "$dir already exists"
+    echo "Remove this directory, or use a new dir="
+    exit 1
+fi
+
+if [ ! -e $msh ]; then
+    if [ $wget = "curl" ]; then
+	# curl $mc3 -o $msh
+	curl -OL $mc3
+    else
+	$wget $mc3 
+    fi
+fi
+
+if [ ! -e $msh ]; then
+    echo "File $msh not found. Wrong version=$version ?"
+    exit 0
+fi
 
 bash $msh -b -p $dir
 
-setenv PATH "$dir/bin:$PATH"
+export PATH="$dir/bin:$PATH"
+conda update -y conda
+pip3 install --upgrade pip
 
-if ($conda) conda update -y conda             # on Ubuntu 18.04.2 LTS this now causes failure when casa6=1
-if ($pip)   pip install --upgrade pip
+#    ensure we have a bash kernel in jupyter notebooks
+pip install bash_kernel
+python -m bash_kernel.install
 
-if (1) then
-  # too many times my /tmp isn't big enough
-  mkdir -p tmp
-  setenv TMPDIR `pwd`/tmp
-endif
+#    write sourceable shell startup recipes
+echo "set path = ($dir/bin "'$path); rehash'  > $dir/python_start.csh
+echo "export PATH=${dir}/bin:"'$PATH'         > $dir/python_start.sh
 
+pip freeze > $dir/freeze.log
+echo "Created python_start files for $version in $dir ; no modifications were made to your HOME startup files!"
+python --version
+echo "typically you would need to "
+echo "      source $dir/python_start.sh"
+echo "to add this python to your shell environment."
 
-echo "set path = ($dir/bin "'$path); rehash'  >> python_start.csh
-echo "export PATH=${dir}/bin:"'$PATH'         >> python_start.sh
-
-echo casa6=$casa6
-if ($casa6) conda install -y python=3.6.8
-
-conda install -y ipython numpy scipy matplotlib notebook jupyter astropy
-
-if ($casa6) then
-  echo "casa6: pip install casatools and casatasks... this will download 740MB"
-  pip install --extra-index-url https://casa-pip.nrao.edu:443/repository/pypi-group/simple casatools
-  pip install --extra-index-url https://casa-pip.nrao.edu:443/repository/pypi-group/simple casatasks
-endif
-
+# conda install -y ipython numpy scipy matplotlib notebook jupyter astropy
 
 # pip install astroquery
 # conda -c astropy astroquery
 
-# install the latest (ALMA is broken in pip/conda, it's too old)
-if (-d astroquery) then
-  source python_start.csh
-  cd astroquery
-  python setup.py install
-else if (1) then
-  source python_start.csh
-  git clone https://github.com/astropy/astroquery
-  cd astroquery
-  python setup.py install
-else
-  pip install --upgrade --pre astroquery
-endif  
-
-pip install image_registration radio_beam reproject spectral_cube
+# pip install image_registration radio_beam reproject spectral_cube
